# Header
menu:
#  Home: /
  Archives: /archives
  Gallery: /gallery
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
#- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /css/images/little.ico
twitter:
google_plus:
fb_admins:
fb_app_id: